services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=Security
      - POSTGRES_USER=sam
      - POSTGRES_PASSWORD=pass